module Petstore6
  module Models
    type pet_update_params =
      {  } & Petstore6::Internal::Type::request_parameters

    class PetUpdateParams < Petstore6::Models::Pet
      extend Petstore6::Internal::Type::RequestParameters::Converter
      include Petstore6::Internal::Type::RequestParameters

      def initialize: (?request_options: Petstore6::request_opts) -> void

      def to_hash: -> { request_options: Petstore6::RequestOptions }
    end
  end
end
